ig.publisher:
  interruptOnError: 
    #interrupt if a single resource fails
    onResource: false
    #interrupt if the publisher module gets an error
    onModule: false
  
  paths:
    # relative to artifacts
    published: published
    # relative to published
    narratives: narratives
    snapshots: snapshots
    website: website
    #relative to resources and resources/project
    templates: templates
    