ig.publisher:
  interruptOnError: 
    #interrupt if a single resource fails
    onResource: false
    #interrupt if the publisher module gets an error
    onModule: false
  
  paths:
    published: published
    narratives: narratives
    snapshots: snapshots
