
ig:
  paths:
    resources: resources
    artifacts: artifacts
    config: config
  
  release: r4
      
  project: sample
  projects:
    sample: 
      name: Sample Profile Set
      folder: sample
      filter: "*.xml"
    another:
      name: Another profile set
      folder: another
      filter: "*.xml"
 
 