
ig:
  paths:
    resources: resources
    artifacts: artifacts
    config: config
      
  package: sample
  packages:
    sample: 
      name: Sample Profile Set
      path: sample
      filter: "*.xml"
    another:
      name: Another profile set
      path: another
      filter: "*.xml"
 
 