ig.validator:
  interruptOnError: 
    #interrupt if a single resource fails
    onResource: false
    #interrupt if the validation module gets an error
    onModule: true
  
  paths:
    validated: validated
  
  