spring:
  profiles:
    active: dev
    include:
      - common
      - validator
      - publisher

ig:
  runner:
    name: "IG Publisher"
  release: r4
#  project: sample
  paths:
    resources: resources
    artifacts: artifacts
    config: config
  projects:
#    sample: 
#      name: Sample Profile Set
#      folder: sample
#      filter: "*.xml"

