spring:
  profiles:
    active: dev
    include:
      - common
      - validator
      - publisher

ig:
  runner:
    name: "IG Publisher"
  #default version for each project
  version: r4
  paths:
    # input files
    resources: resources
    # generated output files
    artifacts: artifacts

#  projects:
#    sample: 
#      name: Sample Profile Set
#      folder: sample
#      filter: "*.xml"  -- default is all files
#      version: r4      -- default is {ig.version}

